name: hacker_news_auto_archiver

on:
    schedule:
        - cron: '0 4 * * *'

    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Installing dependencies
              run: |
                  echo Running 'pip install -r hacker_news_auto_archiver/requirements.txt'
                  pip install -r hacker_news_auto_archiver/requirements.txt

            - name: Run python script
              run: |
                  echo Running 'python hacker_news_auto_archiver/script.py'
                  python hacker_news_auto_archiver/script.py

            - name: Upload to repository
              run: |
                  date > hacker_news_auto_archiver/last_run.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "GitHub Actions Update"
                  git push
