name: snack_stash_data_saver

on:
    schedule:
        - cron: '0 8 * * *'

    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Installing dependencies
              run: |
                  echo Running 'pip install -r snack_stash_data_saver/requirements.txt'
                  pip install -r snack_stash_data_saver/requirements.txt

            - name: Run python script
              run: |
                  echo Running 'python snack_stash_data_saver/script.py'
                  python snack_stash_data_saver/script.py
              env:
                  BUSINESS_AWS_ACCESS_KEY: ${{ secrets.BUSINESS_AWS_ACCESS_KEY }}
                  BUSINESS_AWS_SECRET_KEY: ${{ secrets.BUSINESS_AWS_SECRET_KEY }}
                  BUSINESS_DYNAMODB_TABLE_NAME: ${{ secrets.BUSINESS_DYNAMODB_TABLE_NAME }}
                  BUSINESS_ZEROSHEETS_API_KEY: ${{ secrets.BUSINESS_ZEROSHEETS_API_KEY }}

            - name: Upload to repository
              run: |
                  date > snack_stash_data_saver/last_run.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "GitHub Actions Update"
                  git push
